apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockchain-wallet-exporter.fullname" . }}
  labels:
    {{- include "blockchain-wallet-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
